(in-package :colitrsynth)

(defcmd cmd::cursor-down (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-j+))
  (when (< (max-cursor-y self) (incf (.cursor-y self)))
    (setf (.cursor-y self) 0)))

(defcmd cmd::cursor-left (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-h+))
  (let ((value (- (.cursor-x self)
                  (case (mod (.cursor-x self) +column-width+)
                    (0 2)
                    (4 4)
                    (5 1)
                    (t 0)))))
    (setf (.cursor-x self)
          (if (<= 0 value)
              value
              (max-cursor-x self)))))

(defcmd cmd::cursor-right (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-l+))
  (let* ((value (+ (.cursor-x self)
                   (case (mod (.cursor-x self) +column-width+)
                     (0 4)
                     (4 1)
                     (5 2)
                     (t 0)))))
    (setf (.cursor-x self)
          (if (<= value (max-cursor-x self))
              value
              0))))

(defcmd cmd::cursor-up (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-k+))
  (when (minusp (decf (.cursor-y self)))
    (setf (.cursor-y self) (max-cursor-y self))))

(defcmd cmd::escape (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-escape+))
  (cond ((eq :insert (.mode self))
         (setf (.mode self) :command))
        ((.selection-mode self)
         (setf (.selection-mode self) nil))))

(defcmd cmd::escape-insert-mode (self)
    (:bind (*pattern-editor-insert-keymap* sdl2-ffi:+sdl-scancode-escape+)
      :next-keymap *pattern-editor-keymap*)
  (setf (.mode self) :command))

(defcmd cmd::insert-mode (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-i+)
      :next-keymap *pattern-editor-insert-keymap*)
  ;; TODO mode 必要？
  (setf (.mode self) :insert))

(macrolet ((m (note key)
             (let ((name (intern (format nil "INSERT-NOTE-~a" note) :cmd)))
               `(progn
                  (defcmd ,name (self)
                      (:bind (*pattern-editor-insert-keymap* ,key))
                    (set-note self ,(intern (format nil "~a0" note))))
                  (setf (gethash (list ,key +shift+) *pattern-editor-insert-keymap*)
                        ',name))))
           (m+1 (note key)
             (let ((name (intern (format nil "INSERT-NOTE-~a+1" note) :cmd)))
               `(progn
                  (defcmd ,name (self)
                      (:bind (*pattern-editor-insert-keymap* ,key))
                    (set-note self ,(intern (format nil "~a1" note))))
                  (setf (gethash (list ,key +shift+) *pattern-editor-insert-keymap*)
                        ',name))))
           (m+2 (note key)
             (let ((name (intern (format nil "INSERT-NOTE-~a+2" note) :cmd)))
               `(progn
                  (defcmd ,name (self)
                      (:bind (*pattern-editor-insert-keymap* ,key))
                    (set-note self ,(intern (format nil "~a2" note))))
                  (setf (gethash (list ,key +shift+) *pattern-editor-insert-keymap*)
                        ',name)))))
  ;; http://sdl2referencejp.osdn.jp/SDLScancodeLookup.html
  (m c sdl2-ffi:+sdl-scancode-z+)
  (m c# sdl2-ffi:+sdl-scancode-s+)
  (m d sdl2-ffi:+sdl-scancode-x+)
  (m d# sdl2-ffi:+sdl-scancode-d+)
  (m e sdl2-ffi:+sdl-scancode-c+)
  (m f sdl2-ffi:+sdl-scancode-v+)
  (m f# sdl2-ffi:+sdl-scancode-g+)
  (m g sdl2-ffi:+sdl-scancode-b+)
  (m g# sdl2-ffi:+sdl-scancode-h+)
  (m a sdl2-ffi:+sdl-scancode-n+)
  (m a# sdl2-ffi:+sdl-scancode-j+)
  (m b sdl2-ffi:+sdl-scancode-m+)
  (m+1 c sdl2-ffi:+sdl-scancode-comma+)
  (m+1 c# sdl2-ffi:+sdl-scancode-l+)
  (m+1 d sdl2-ffi:+sdl-scancode-period+)
  (m+1 d# sdl2-ffi:+sdl-scancode-semicolon+)
  (m+1 e sdl2-ffi:+sdl-scancode-slash+)
  (m+1 f sdl2-ffi:+sdl-scancode-nonusbackslash+)
  (m+1 f# sdl2-ffi:+sdl-scancode-backslash+)
  (m+1 c sdl2-ffi:+sdl-scancode-q+)
  (m+1 c# sdl2-ffi:+sdl-scancode-2+)
  (m+1 d sdl2-ffi:+sdl-scancode-w+)
  (m+1 d# sdl2-ffi:+sdl-scancode-3+)
  (m+1 e sdl2-ffi:+sdl-scancode-e+)
  (m+1 f sdl2-ffi:+sdl-scancode-r+)
  (m+1 f# sdl2-ffi:+sdl-scancode-5+)
  (m+1 g sdl2-ffi:+sdl-scancode-t+)
  (m+1 g# sdl2-ffi:+sdl-scancode-6+)
  (m+1 a sdl2-ffi:+sdl-scancode-y+)
  (m+1 a# sdl2-ffi:+sdl-scancode-7+)
  (m+1 b sdl2-ffi:+sdl-scancode-u+)
  (m+2 c sdl2-ffi:+sdl-scancode-i+)
  (m+2 c# sdl2-ffi:+sdl-scancode-9+)
  (m+2 d sdl2-ffi:+sdl-scancode-o+)
  (m+2 d# sdl2-ffi:+sdl-scancode-0+)
  (m+2 e sdl2-ffi:+sdl-scancode-p+)
  (m+2 f sdl2-ffi:+sdl-scancode-leftbracket+) ;@
  (m+2 f# sdl2-ffi:+sdl-scancode-equals+) ;^
  (m+2 g sdl2-ffi:+sdl-scancode-rightbracket+)  ;[
  (m+2 g# sdl2-ffi:+sdl-scancode-international3+) ;\
  )


(defcmd cmd::insert-note-c (self)
    (:bind (*pattern-editor-insert-keymap* sdl2-ffi:+sdl-scancode-z+))
  (set-note self c0))

(defcmd cmd::paste (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-p+))
  (awhen (deserialize (sdl2-ffi.functions:sdl-get-clipboard-text))
    (cond ((typep it 'line)
           (setf (.current-line self) it))
          ((and (typep it 'cons)
                (typep (car it) 'line))
           (loop for i from (.cursor-y self) below (.length (.pattern self))
                 for line in it
                 do (setf (aref (.lines (.pattern self)) i) line))))))

(defcmd cmd::selection-mode-block (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-v+ +ctrl+)
      :next-keymap *pattern-editor-selection-block-keymap*)
  (setf (.selection-mode self) :block)
  (setf (.selection-start self) (.cursor-y self)))

(defcmd cmd::selection-mode-line (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-v+ +shift+)
     :next-keymap *pattern-editor-selection-line-keymap*)
  (setf (.selection-mode self) :line)
  (setf (.selection-start self) (.cursor-y self)))

(defcmd cmd::yank (self)
    (:bind (*pattern-editor-keymap* sdl2-ffi:+sdl-scancode-y+)
      :next-keymap *pattern-editor-yank-keymap*))

(defcmd cmd::yank-line (self)
    (:bind (*pattern-editor-yank-keymap* sdl2-ffi:+sdl-scancode-y+)
      :next-keymap *pattern-editor-keymap*)
  (sdl2-ffi.functions:sdl-set-clipboard-text
   (with-serialize-context (out)
     (write (serialize (.current-line self)) :stream out))))

(defcmd cmd::yank-selection-lines (self)
    (:bind (*pattern-editor-selection-line-keymap* sdl2-ffi:+sdl-scancode-y+)
      :next-keymap *pattern-editor-keymap*)
  (let* ((start  (.cursor-y self))
         (end (.selection-start self))
         (lines (loop for i from (min start end) to (max start end)
                      collect (aref (.lines (.pattern self)) i))))
    (sdl2-ffi.functions:sdl-set-clipboard-text
     (with-serialize-context (out)
       (write (serialize lines) :stream out))))
  (setf (.selection-mode self) nil)
  ;; TODO カーソル位置を選択開始位置に戻すべき？ vim は戻している
  )
