(in-package :colitrsynth)

(defcmd cmd::transpose ((self pattern-module) delta) (:interactive t)
  (let* ((editor (.editor self))
         (from (if (eq (.selection-mode editor) :line)
                   (min (.selection-start editor)
                        (.cursor-y editor))
                   0))
         (to (if (eq (.selection-mode editor) :line)
                 (min (.selection-start editor)
                      (.cursor-y editor))
                 (1- (length (.lines self))))))
    (loop for i from from to to
          for line = (aref (.lines self) i)
          do (loop for column across (.columns line)
                   if (valid-note-p (.note column))
                     do (setf (.note column)
                              (min ga (max c0 (+ (.note column) delta))))))))
